# https://docs.rubocop.org/rubocop/1.10/
# rubocopを実行した際に 「--require」コマンドで自動で読み込まれる
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'spec/**/*'

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Naming/VariableNumber:
  Enabled: :snake_case

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/MethodLength
Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc', 'hash']
