protocol: https
host: arrangy.jp
google:
  callback_url: https://arrangy.jp/api/oauth/callback?provider=google
twitter:
  callback_url: https://arrangy.jp/api/oauth/callback?provider=twitter
aws:
  bucket: arrangy
